global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'backend'
    metrics_path: '/metrics'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: backend
        action: keep

  - job_name: 'redis-exporter'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: redis
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: metrics;?;
        action: keep

  - job_name: 'postgres-exporter'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: postgres
        action: keep

  - job_name: 'static-local'
    static_configs:
      - targets: ['backend:8000','redis-exporter:9121','postgres-exporter:9187']