apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: cloud-blog-backend:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres:5432/postgres"
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        ports:
        - containerPort: 8000
