apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:change_me_postgres_password@postgres:5432/postgres"
  REDIS_URL: "redis://redis:6379/0"