name: CI Pipeline

permissions:
  contents: read
  packages: write
  id-token: write
  pull-requests: write

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: lentra0

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: postgres
        options: >-
          --health-cmd "pg_isready -U postgres -d postgres -h localhost"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 30
      redis:
        image: redis:6.2-alpine
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker info
        run: |
          docker version
          docker info

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/backend:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/backend:${{ github.sha }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/frontend:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/frontend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube /usr/local/bin/minikube

      - name: Start minikube
        run: |
          sudo minikube start --driver=docker --memory=4096 --cpus=2

      - name: Build and load backend image into minikube
        run: |
          docker build -t blog-backend:ci ./backend
          minikube image load blog-backend:ci

      - name: Build and load frontend image into minikube
        run: |
          docker build -t blog-frontend:ci ./frontend
          minikube image load blog-frontend:ci

      - name: Create Kubernetes secrets in Minikube
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          GF_PASSWORD: ${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}
        run: |
          kubectl create secret generic postgres-secrets \
            --from-literal=POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
            --dry-run=client -o yaml | kubectl apply -f -

          kubectl create secret generic backend-secrets \
            --from-literal=DATABASE_URL="postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres" \
            --dry-run=client -o yaml | kubectl apply -f -

          kubectl create secret generic grafana-secrets \
            --from-literal=GF_SECURITY_ADMIN_PASSWORD="${GF_PASSWORD}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Update manifests to use CI images and apply
        run: |
          sed -i "s|image: cloud-blog-backend:0.1.0|image: blog-backend:ci|g" kubernetes/backend-deployment.yaml || true
          sed -i "s|image: cloud-blog-frontend:0.1.0|image: blog-frontend:ci|g" kubernetes/frontend-deployment.yaml || true
          kubectl apply -f kubernetes/

      - name: Wait for rollouts
        run: |
          kubectl rollout status deployment/backend --timeout=120s || true
          kubectl rollout status deployment/frontend --timeout=120s || true

      - name: Show Minikube IP and resource status
        run: |
          echo "Minikube IP: $(minikube ip)"
          kubectl get nodes -o wide
          kubectl get pods --all-namespaces -o wide
          kubectl get svc --all-namespaces -o wide
